services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6380:6379" # Redis exposto na porta 6380

  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq
    ports:
      - "5672:5672"   # Porta de comunicação do RabbitMQ (AMQP)
      - "15672:15672" # Painel de administração do RabbitMQ
    environment:
      RABBITMQ_DEFAULT_USER: guest # Usuário padrão
      RABBITMQ_DEFAULT_PASS: guest # Senha padrão 

  api_order:
    image: api_order    
    ports:
      - "5001:80"
    environment:
      - RABBITMQ_CONNECTION=rabbitmq:5672
    depends_on:
      - rabbitmq

  api_sale:
    image: api_sale    
    ports:
      - "5002:80"  
    environment:
      - RABBITMQ_CONNECTION=rabbitmq:5672
    depends_on:
      - rabbitmq      

  api_stock:
    image: api_stock    
    ports:
      - "5003:80"
    environment:
      - REDIS_CONNECTION=redis:6379
      - RABBITMQ_CONNECTION=rabbitmq:5672
    depends_on:
      - redis    
      - rabbitmq        

  app_angular:
    image: app-angular  
    ports:
      - "4200:80"

  gateway:
    image: api_gateway  
    ports:
      - "4000:80" # Porta exposta
    depends_on:
      - api_order
      - api_sale
      - api_stock   
