// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SharedDatabase.Models;

[Table("ordersalestatus")]
public partial class Ordersalestatus
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("idorder")]
    public int? Idorder { get; set; }

    [Column("idsale")]
    public int? Idsale { get; set; }

    [Column("idstatus")]
    public int? Idstatus { get; set; }

    [Column("namestatus")]
    [StringLength(45)]
    public string Namestatus { get; set; }

    [Column("message")]
    [StringLength(45)]
    public string Message { get; set; }
}